### PR TITLE
Landing Page Animation

### PR DESCRIPTION
**Pull request by auxfuse**
### Description:
***
This PR creates a default landing page that renders on User first visit.

### Feature details:
***
- index.html template created (and added to templates directory) with default view function in app.py.
- Minimalistic theme to contrast the explosive color of the website on entry.
- Utilises Font Awesome heart icon with hover affect animation.
- On click of the heart icon, scale animation is triggered via CSS, and user is redirected to actual "home" page used on the site.
- Appropriate Javascript set to add to animation effects, and to redirect user.
- Small quality of life improvements to some files including:
        - app.py, enconding parameter set on `flags()` view function
        - chevron icon swapped for heart icon in index.html
        - home.html & support.html default templates added to templates directory
        - small typo fixes, line spacing and indentation added to style.css

### Accompanying Screenshots & visual details:
***
https://user-images.githubusercontent.com/48055438/122651361-32738900-d130-11eb-8a0a-f5080048c187.mp4

### CODE REVIEW

**Review by lemocla — COMMENTED** [review]
LGTM 🌈 🦄

**Review by andrewdempsey2018 — APPROVED** [review]
LGTM

**Comment by lemocla** [comment]
Closing PR #25

**Review by lemocla — APPROVED** [review]
LGTM - APPROVED

**Comment by lemocla** [comment]
Closing PR #25

**Pull request merged**
