### PR TITLE
Supportpage

### PR DESCRIPTION
**Pull request by lemocla**
- Added paragraph to flag page
- Amended style for flag page (such as figure and image - as not to override default styling and affecting other pages)
- Added content to support page as follows:
        * Introduction support page
        * Image
        * Carousel with flickity showcasing lgbtq+ advocates 
   
- Added data to json file (although some links are creating warning in console log)
- Updated base.html with cdn links for flickity carousel

### CODE REVIEW

**Review by andrewdempsey2018 — APPROVED** [review]
LGTM except for conflicts

**Comment by auxfuse** [comment]
Can you resolve Merge Conflicts please? 😁 @lemocla

**Review by andrewdempsey2018 — APPROVED** [review]
LGTM

**Comment by andrewdempsey2018** [comment]
Reviewed and closed PR #31

**Pull request merged**
